version: "3"
services:
  hub:
    image: selenium/hub:4.27
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_ENABLE_TRACING=false
  chrome:
    image: selenium/node-chromium:4.27
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_ENABLE_TRACING=false
  firefox:
    image: selenium/node-firefox:4.27
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_ENABLE_TRACING=false
  vendor-portal:
    image: vlasovandrei/automation_selenium
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: vlasovandrei/automation_selenium
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output